---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sherpa-users.fullname" . }}-configmap
  labels:
    {{- include "sherpa-users.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/init.sql").AsConfig | indent 2 }}