apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sherpa-users.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "sherpa-users.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
